Script started on 2026-06-25 22:12:08+02:00 [TERM="xterm-256color" TTY="/dev/pts/2" COLUMNS="94" LINES="46"]
[1m[7m%[27m[1m[0m                                                                                              ]2;pulgamecanica@pulgamecanica:~/42Org/boot2root]1;..Org/boot2root]7;file://pulgamecanica/home/pulgamecanica/42Org/boot2root\[0m[27m[24m[J(base) [01;31m➜  [36mboot2root[00m [K[?1h=[?2004h[0m[27m[24m[J(base) [01;31m➜  [36mboot2root[00m [01;34mgit:([31mmain[34m) [33m✗[00m [Kbbash scripts[1m/[0m[0m/inusers.info[1m [0m[0m           
[0mdecode_turtle.py  ftpsh.py          root_exploit.sh                                   
[Jfile.sh           [Jrebuild_code.sh   [Jusers.info        [J                                [A[A[0m[27m[24m[33Cbash scripts/[K[?2004l
[J[1m[7m%[27m[1m[0m                                                                                              ]2;pulgamecanica@pulgamecanica:~/42Org/boot2root]1;..Org/boot2root]7;file://pulgamecanica/home/pulgamecanica/42Org/boot2root\[0m[27m[24m[J(base) [01;31m➜  [36mboot2root[00m [01;34mgit:([31mmain[34m) [33m✗[00m [K[?1h=[?2004heexit[?1l>[?2004l
]2;exit]1;exit
Script done on 2026-06-25 22:12:32+02:00 [COMMAND_EXIT_CODE="130"]
